include ../shared.conf

# This maps Cmd to Ctrl for the most common navigation keys
map cmd+a send_text all \x01
map cmd+b send_text all \x02
map cmd+c send_text all \x03
map cmd+d send_text all \x04
map cmd+e send_text all \x05
map cmd+f send_text all \x06
map cmd+g send_text all \x07
map cmd+h send_text all \x08
map cmd+j send_text all \x0a
map cmd+k send_text all \x0b
map cmd+l send_text all \x0c
map cmd+p send_text all \x10
map cmd+r send_text all \x12
map cmd+t send_text all \x14
map cmd+u send_text all \x15
map cmd+v send_text all \x16
map cmd+w send_text all \x17
map cmd+x send_text all \x18
map cmd+z send_text all \x1a
map cmd+h send_text all \x08
map cmd+w send_text all \x17
map cmd+q send_text all \x11
map cmd+n send_text all \x0e
map cmd+p send_text all \x10
map cmd+i send_text all \x1b[105;5u
map cmd+o send_text all \x1b[111;5u
map cmd+1 send_text all \x1b[49;5u
map cmd+2 send_text all \x1b[50;5u
map cmd+3 send_text all \x1b[51;5u
map cmd+4 send_text all \x1b[52;5u
map cmd+/ send_text all \x1f

# This sends a "paste" command to the terminal
map cmd+v paste_from_clipboard

# Cmd+Shift+H/L to switch tmux windows
map cmd+shift+h send_text all \x1bH
map cmd+shift+l send_text all \x1bL

# This tells Kitty to treat the Option key as 'Alt' (Meta)
macos_option_as_alt yes

# Maps Cmd+S to send the :w (write) command followed by Enter (\r)
map cmd+s send_text all :w\r
