# --- General Settings ---
unbind C-b
bind C-a send-prefix
set -g status-position top
set -g automatic-rename on
set -g automatic-rename-format "#{pane_current_command}"

# Support images
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# bind windows navigation
# Cmd+Shift+H/L mapped via terminal emulator sending custom escape sequences
bind-key -n M-H previous-window
bind-key -n M-L next-window

# --- Catppuccin Config (Themed UI) ---
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text " #{pane_current_command}"
set -g @catppuccin_window_current_text " #{pane_current_command}"

# --- Status Bar Layout ---
set -g status-left-length 100
set -g status-right-length 100
set -g status-left ""

# Right side: Session Name | Date/Time | Continuum Status
set -g status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_date_time}"
# Custom pill for your Continuum Save Status
set -ag status-right "#[fg=#{@thm_green},bg=#{@thm_surface_0}] 󱑖 #{continuum_status}m "

# --- Continuum & Resurrect Settings ---
set -g @continuum-restore 'on'
set -g @continuum-save-interval '10'
